apiRules:
- exclude:
    uidRegex: ^OnTopic\.Repositories.*$
    type: Type
- exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute
- exclude:
    uidRegex: ^OnTopic\.Internal\..*$
    type: Namespace